name: Continuous Integration

on:
  pull_request:
    branches: ['**']
    types: [opened, reopened]
  push:
    branches: ['**']


jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '11'

      - name: Run tests
        run: |
          sbt test

